title:              BM-docs
email:              burnman108@126.com
description:        Something changes, and something will be go on!
author:             BurnMan
baseurl:            ""
url:                "https://burnman108.github.io"

# Social Profiles
twitter_username:   
github_username:    burnman108
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site


# Set the time zone for site generation
timezone: Europe/Amsterdam